export const islands = [
  {
    id: "santo-antao",
    name: "Santo Antão",
    tagline: "Onde as montanhas encontram a alma.",
    description: "A ilha mais a oeste, com picos vulcânicos, vales profundos e trilhos de montanha únicos no mundo.",
    image: "/images/santoAntao.png",
    temperature: "24°C",
    highlights: [
      { name: "Trekking", description: "As mais dramáticas rotas do arquipélago, pelo Vale do Paul e cristas vulcânicas com vistas directas para o oceano." },
      { name: "Vale do Paul", description: "Vale verdejante de coqueiros e bananeiras com levadas de água centenárias e aldeias escondidas nas montanhas." },
      { name: "Grogue", description: "A aguardente de cana-de-açúcar cabo-verdiana. Visita às destilarias artesanais do vale — tradição viva desde o séc. XVII." },
      { name: "Ribeira Grande", description: "Principal cidade da ilha, com mercado local autêntico, praça colonial e o melhor ponto de partida para os trilhos." },
    ],
    en: {
      tagline: "Where the mountains meet the soul.",
      description: "The westernmost island, with volcanic peaks, deep valleys and mountain trails unlike anywhere else in the world.",
      highlights: [
        { name: "Trekking", description: "The most dramatic trails in the archipelago, through Paul Valley and volcanic ridges with direct ocean views." },
        { name: "Paul Valley", description: "Lush valley of coconut and banana trees with century-old water channels and villages hidden in the mountains." },
        { name: "Grogue", description: "Cape Verde's sugarcane spirit. Visit the artisanal distilleries of the valley — a living tradition since the 17th century." },
        { name: "Ribeira Grande", description: "The island's main town, with an authentic local market, colonial square and the best starting point for the trails." },
      ],
    },
    duration: "3–5 dias",
    color: "#1a4a3a",
    svgX: 88,
    svgY: 72,
  },
  {
    id: "sao-vicente",
    name: "São Vicente",
    tagline: "A ilha que canta.",
    description: "Mindelo, a capital cultural de Cabo Verde. Uma cidade de música, arte, carnaval e morabeza.",
    image: "/images/saovicente.png",
    temperature: "26°C",
    highlights: [
      { name: "Mindelo", description: "A capital cultural de Cabo Verde. Ruas coloridas, bares de morna ao vivo e uma energia que só existe aqui." },
      { name: "Carnaval", description: "O maior Carnaval de Cabo Verde, comparado ao de Notting Hill. Desfiles de máscaras, cor e identidade pura em Fevereiro." },
      { name: "Morna", description: "O género musical Património Imaterial da UNESCO. Nasceu aqui, na voz imortal de Cesária Évora." },
      { name: "Porto Grande", description: "Um dos maiores portos naturais da África Ocidental. Ponto de encontro histórico de navios, culturas e histórias." },
    ],
    en: {
      tagline: "The island that sings.",
      description: "Mindelo, Cape Verde's cultural capital. A city of music, art, carnival and morabeza.",
      highlights: [
        { name: "Mindelo", description: "Cape Verde's cultural capital. Colourful streets, live morna bars and an energy that exists nowhere else." },
        { name: "Carnival", description: "Cape Verde's biggest Carnival, compared to Notting Hill. Costume parades, colour and pure identity every February." },
        { name: "Morna", description: "The musical genre that is UNESCO Intangible Heritage. Born here, in the immortal voice of Cesária Évora." },
        { name: "Porto Grande", description: "One of the largest natural harbours in West Africa. A historic meeting point of ships, cultures and stories." },
      ],
    },
    duration: "2–4 dias",
    color: "#0d3a6e",
    svgX: 138,
    svgY: 95,
  },
  {
    id: "santa-luzia",
    name: "Santa Luzia",
    tagline: "O último paraíso desabitado.",
    description: "A única ilha desabitada do arquipélago. Natureza intocada, tartarugas e silêncio absoluto.",
    image: "/images/santaluzia.png",
    temperature: "25°C",
    highlights: [
      { name: "Natureza virgem", description: "A única ilha desabitada do arquipélago. Acesso apenas por barco, sem estradas nem electricidade — o mundo como era." },
      { name: "Tartarugas", description: "Nidificação de tartarugas-careta nas praias remotas. Uma das mais importantes áreas de desova da Macaronésia." },
      { name: "Mergulho", description: "Águas cristalinas sem perturbação humana. Biodiversidade marinha excepcional com visibilidade de 25m+ o ano todo." },
    ],
    en: {
      tagline: "The last uninhabited paradise.",
      description: "The only uninhabited island in the archipelago. Untouched nature, sea turtles and absolute silence.",
      highlights: [
        { name: "Virgin nature", description: "The only uninhabited island in the archipelago. Access by boat only, no roads or electricity — the world as it once was." },
        { name: "Sea turtles", description: "Loggerhead turtle nesting on remote beaches. One of the most important nesting areas in Macaronesia." },
        { name: "Diving", description: "Crystal-clear waters undisturbed by humans. Exceptional marine biodiversity with 25m+ visibility year-round." },
      ],
    },
    duration: "Excursão de dia",
    color: "#1a5c3a",
    svgX: 190,
    svgY: 108,
  },
  {
    id: "sao-nicolau",
    name: "São Nicolau",
    tagline: "Beleza que guarda segredos.",
    description: "Ilha montanhosa e serena, com um interior verde e uma cultura profundamente enraizada.",
    image: "/images/sao-nicolau.png",
    temperature: "25°C",
    highlights: [
      { name: "Ribeira Brava", description: "A vila mais pitoresca do Barlavento Norte, com casas coloridas nas encostas e uma atmosfera de tempo parado." },
      { name: "Monte Gordo", description: "Pico verde no centro da ilha com vistas de 360° para o oceano. Trekking acessível para todos os níveis." },
      { name: "Artesanato", description: "Cerâmica, bordados e cestaria produzidos segundo técnicas tradicionais. O melhor artesanato local do arquipélago." },
    ],
    en: {
      tagline: "Beauty that keeps secrets.",
      description: "A mountainous, serene island with a green interior and a deeply rooted culture.",
      highlights: [
        { name: "Ribeira Brava", description: "The most picturesque town in the Northern Barlavento, with colourful hillside houses and a timeless atmosphere." },
        { name: "Monte Gordo", description: "Green peak at the island's centre with 360° ocean views. Accessible trekking for all levels." },
        { name: "Handicrafts", description: "Ceramics, embroidery and basketry made using traditional techniques. The archipelago's finest local crafts." },
      ],
    },
    duration: "2–3 dias",
    color: "#2d5a1a",
    svgX: 282,
    svgY: 130,
  },
  {
    id: "sal",
    name: "Sal",
    tagline: "Horizonte, vento e liberdade.",
    description: "Praias de areia branca, kitesurf e mergulho. Onde o deserto encontra o oceano atlântico.",
    image: "/images/sal.png",
    temperature: "28°C",
    highlights: [
      { name: "Kitesurf", description: "Santa Maria é um dos melhores spots de kitesurf do mundo. Vento alísio constante todo o ano com escola certificada IKO." },
      { name: "Santa Maria", description: "A vila mais animada do Sal. Rua Direita cheia de restaurantes, bares de pôr do sol e lojas de surf à beira-mar." },
      { name: "Mergulho", description: "Recifes de coral, grutas submarinas e tartarugas. Visibilidade de 20m+ em águas a 24°C durante todo o ano." },
      { name: "Salinas", description: "As antigas salinas que deram nome à ilha. Hoje um ecossistema de flamingos e aves migratórias de todo o Atlântico." },
    ],
    en: {
      tagline: "Horizon, wind and freedom.",
      description: "White sand beaches, kitesurfing and diving. Where the desert meets the Atlantic ocean.",
      highlights: [
        { name: "Kitesurfing", description: "Santa Maria is one of the world's best kitesurfing spots. Constant trade winds year-round with an IKO-certified school." },
        { name: "Santa Maria", description: "Sal's most vibrant village. The Rua Direita packed with restaurants, sunset bars and surf shops by the sea." },
        { name: "Diving", description: "Coral reefs, underwater caves and sea turtles. 20m+ visibility in 24°C waters throughout the year." },
        { name: "Salt pans", description: "The ancient salt pans that gave the island its name. Today an ecosystem of flamingos and migratory birds from across the Atlantic." },
      ],
    },
    duration: "3–7 dias",
    color: "#5c3a1a",
    svgX: 548,
    svgY: 110,
  },
  {
    id: "boa-vista",
    name: "Boa Vista",
    tagline: "Dunas e mar sem fim.",
    description: "Deserto de dunas de areia dourada que mergulham no Atlântico. Tartarugas que desovam nas praias.",
    image: "/images/boavista.png",
    temperature: "27°C",
    highlights: [
      { name: "Deserto de Dunas", description: "Dunas de areia do Saara que encontram o Atlântico. Um cenário lunar que não existe em mais nenhum outro lugar do arquipélago." },
      { name: "Tartarugas", description: "Praia de Ervatão: uma das maiores áreas de desova de tartaruga-careta do mundo. Saídas nocturnas guiadas de Junho a Outubro." },
      { name: "Kitesurf", description: "Ventos alísios constantes e uma lagoa de água azul-turquesa tornam Boa Vista num paraíso do kitesurf e windsurf." },
      { name: "Sal Rei", description: "A única cidade da ilha. Mercado de peixe ao amanhecer, praças coloniais e os melhores pratos de lagosta fresca." },
    ],
    en: {
      tagline: "Dunes and endless sea.",
      description: "Desert of golden sand dunes plunging into the Atlantic. Sea turtles nesting on the beaches.",
      highlights: [
        { name: "Sand dune desert", description: "Sahara sand dunes meeting the Atlantic. A lunar landscape found nowhere else in the archipelago." },
        { name: "Sea turtles", description: "Ervatão Beach: one of the world's largest loggerhead turtle nesting areas. Guided night walks from June to October." },
        { name: "Kitesurfing", description: "Constant trade winds and a turquoise lagoon make Boa Vista a paradise for kitesurfing and windsurfing." },
        { name: "Sal Rei", description: "The island's only town. Dawn fish market, colonial squares and the freshest lobster dishes you'll find anywhere." },
      ],
    },
    duration: "3–5 dias",
    color: "#6b4a1a",
    svgX: 572,
    svgY: 188,
  },
  {
    id: "maio",
    name: "Maio",
    tagline: "Calma, sal e identidade.",
    description: "A ilha mais tranquila. Salinas, praias desertas e uma comunidade que vive ao ritmo do mar.",
    image: "/images/maio.png",
    temperature: "26°C",
    highlights: [
      { name: "Praias desertas", description: "Quilómetros de praia de areia branca sem um único guarda-sol. A Praia do Pau Seco é praticamente um segredo guardado." },
      { name: "Salinas", description: "Paisagem de sapal e salineiras em actividade. Flamingos cor-de-rosa em grandes bandos — um espectáculo raro no Atlântico." },
      { name: "Aldeias tradicionais", description: "Ribeira Dom João e Calheta: aldeias piscatórias onde o tempo parou e a hospitalidade cabo-verdiana está na sua forma mais pura." },
    ],
    en: {
      tagline: "Calm, salt and identity.",
      description: "The quietest island. Salt pans, deserted beaches and a community that lives at the rhythm of the sea.",
      highlights: [
        { name: "Deserted beaches", description: "Kilometres of white sand beach without a single sunlounger. Pau Seco Beach is practically a kept secret." },
        { name: "Salt pans", description: "Salt marsh and active saltworks landscape. Pink flamingos in large flocks — a rare spectacle in the Atlantic." },
        { name: "Traditional villages", description: "Ribeira Dom João and Calheta: fishing villages where time stood still and Cape Verdean hospitality is at its purest." },
      ],
    },
    duration: "2–3 dias",
    color: "#3a5c1a",
    svgX: 500,
    svgY: 300,
  },
  {
    id: "santiago",
    name: "Santiago",
    tagline: "Onde a história criou raízes.",
    description: "A maior ilha. Cidade Velha, patrimônio da UNESCO, a capital Praia, e a alma crioula de Cabo Verde.",
    image: "/images/santiago.png",
    temperature: "27°C",
    highlights: [
      { name: "Cidade Velha", description: "Primeiro núcleo urbano europeu nos trópicos. Património Mundial UNESCO — o berço da civilização cabo-verdiana e da língua crioula." },
      { name: "Praia", description: "A capital do país. Praias urbanas, vida nocturna, mercado do Sucupira e a baía ao pôr do sol com vista para o Platô." },
      { name: "Tarrafal", description: "A norte da ilha, com uma das mais belas baías de Cabo Verde e o histórico campo de concentração do Estado Novo." },
      { name: "Platô", description: "Centro histórico da capital. Ruas calcetadas, Praça Alexandre Albuquerque e a vista do escarpado basáltico para o porto." },
    ],
    en: {
      tagline: "Where history took root.",
      description: "The largest island. Cidade Velha, a UNESCO World Heritage Site, the capital Praia, and the Creole soul of Cape Verde.",
      highlights: [
        { name: "Cidade Velha", description: "First European urban settlement in the tropics. UNESCO World Heritage — the birthplace of Cape Verdean civilisation and the Creole language." },
        { name: "Praia", description: "The country's capital. Urban beaches, nightlife, the Sucupira market and the bay at sunset with views of the Plateau." },
        { name: "Tarrafal", description: "In the north of the island, with one of Cape Verde's most beautiful bays and the historic Estado Novo concentration camp." },
        { name: "Plateau", description: "The historic city centre. Cobblestone streets, Praça Alexandre Albuquerque and views from the basalt escarpment over the harbour." },
      ],
    },
    duration: "4–7 dias",
    color: "#1a3a6e",
    svgX: 408,
    svgY: 318,
  },
  {
    id: "fogo",
    name: "Fogo",
    tagline: "Uma ilha nascida do fogo.",
    description: "O vulcão Pico do Fogo domina a paisagem. Vinho produzido em solos vulcânicos e uma cultura única.",
    image: "/images/fogo.png",
    temperature: "25°C",
    highlights: [
      { name: "Pico do Fogo", description: "O ponto mais alto de Cabo Verde (2.829m). Ascensão ao cone activo com guia local — uma das experiências mais raras do Atlântico." },
      { name: "Vinho do Fogo", description: "Vinho produzido em solos de lava vulcânica dentro da caldeira. Um sabor único que não existe em mais nenhum lugar do mundo." },
      { name: "Chã das Caldeiras", description: "Aldeia de mil habitantes dentro de um vulcão activo. Uma das comunidades mais extraordinárias e resilientes do planeta." },
      { name: "Trekking", description: "Percursos pela orla da caldeira com vistas de 360° sobre o mar de nuvens e a sensação de estar num mundo perdido no tempo." },
    ],
    en: {
      tagline: "An island born of fire.",
      description: "The Pico do Fogo volcano dominates the landscape. Wine produced on volcanic soils and a truly unique culture.",
      highlights: [
        { name: "Pico do Fogo", description: "Cape Verde's highest point (2,829m). Ascent to the active cone with a local guide — one of the rarest experiences in the Atlantic." },
        { name: "Fogo Wine", description: "Wine produced in volcanic lava soils inside the caldera. A unique flavour that exists nowhere else in the world." },
        { name: "Chã das Caldeiras", description: "A thousand-person village inside an active volcano. One of the most extraordinary and resilient communities on the planet." },
        { name: "Trekking", description: "Trails along the caldera rim with 360° views over the sea of clouds, feeling like a world lost in time." },
      ],
    },
    duration: "2–4 dias",
    color: "#6e1a1a",
    svgX: 252,
    svgY: 332,
  },
  {
    id: "brava",
    name: "Brava",
    tagline: "A ilha das flores e da saudade.",
    description: "A menor ilha habitada. Famosa pelas flores, pela poesia e pela diáspora americana.",
    image: "/images/brava.png",
    temperature: "24°C",
    highlights: [
      { name: "Ilha das Flores", description: "Hibiscos, bougainvíleas e jardins em terraços perfumados. A mais verde e florida de todas as ilhas do arquipélago." },
      { name: "Nova Sintra", description: "A vila mais encantadora de Cabo Verde. Silêncio, casas coloridas envoltas em nuvens e o melhor café crioulo da ilha." },
      { name: "Diáspora", description: "A ilha com maior percentagem de emigrantes — muitos na Nova Inglaterra, EUA. Música de saudade que atravessa o Atlântico." },
      { name: "Segredo preservado", description: "Sem resorts, sem turismo de massa. Brava é o segredo que os cabo-verdianos guardam para si próprios. Chegue antes dos outros." },
    ],
    en: {
      tagline: "The island of flowers and longing.",
      description: "The smallest inhabited island. Famous for its flowers, its poetry and its American diaspora.",
      highlights: [
        { name: "Island of Flowers", description: "Hibiscus, bougainvillea and perfumed terraced gardens. The greenest and most flowery of all the archipelago's islands." },
        { name: "Nova Sintra", description: "Cape Verde's most enchanting village. Silence, colourful houses wrapped in clouds and the best Creole coffee on the island." },
        { name: "Diaspora", description: "The island with the highest proportion of emigrants — many in New England, USA. Music of longing that crosses the Atlantic." },
        { name: "Preserved secret", description: "No resorts, no mass tourism. Brava is the secret Cape Verdeans keep for themselves. Arrive before the others do." },
      ],
    },
    duration: "2–3 dias",
    color: "#3a1a6e",
    svgX: 175,
    svgY: 342,
  },
];

export type IslandHighlight = { name: string; description: string };
export type Island = (typeof islands)[number] & {
  tagline: string;
  description: string;
  highlights: IslandHighlight[];
};

export function localizeIsland(island: typeof islands[number], locale: string): Island {
  if (locale === "en" && island.en) {
    return { ...island, tagline: island.en.tagline, description: island.en.description, highlights: island.en.highlights };
  }
  return island as Island;
}

export function getLocalizedIslands(locale: string): Island[] {
  return islands.map((island) => localizeIsland(island, locale));
}

export const cultureItems = [
  {
    id: "morna",
    name: "Morna",
    description: "A alma musical de Cabo Verde. Saudade que atravessa o Atlântico.",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    icon: "♪",
    color: "#082B5C",
  },
  {
    id: "funana",
    name: "Funaná",
    description: "Ritmo quente e contagiante das tabancas de Santiago.",
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&q=80",
    icon: "🎵",
    color: "#3a1a6e",
  },
  {
    id: "batuque",
    name: "Batuque",
    description: "Percussão ancestral das mulheres de Santiago. Poder e resistência.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    icon: "🥁",
    color: "#6e1a1a",
  },
  {
    id: "coladeira",
    name: "Coladeira",
    description: "Leveza e alegria. A dança da festa e da celebração cabo-verdiana.",
    image: "https://images.unsplash.com/photo-1526218626217-dc65a29bb444?w=800&q=80",
    icon: "💃",
    color: "#1a5c3a",
  },
  {
    id: "carnaval",
    name: "Carnaval de Mindelo",
    description: "O maior espectáculo das ilhas. Cor, fantasia e energia atlântica.",
    image: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&q=80",
    icon: "🎭",
    color: "#C9A05E",
  },
  {
    id: "tabanka",
    name: "Tabanka",
    description: "Tradição afro-cabo-verdiana de Santiago. Música, dança e comunidade.",
    image: "https://images.unsplash.com/photo-1565031491910-e57fac031c41?w=800&q=80",
    icon: "🎶",
    color: "#0d3a6e",
  },
  {
    id: "artesanato",
    name: "Artesanato",
    description: "Tecidos panu di terra, cerâmica e fibras naturais. Arte que conta histórias.",
    image: "https://images.unsplash.com/photo-1555507036-ab794f575ecd?w=800&q=80",
    icon: "🧵",
    color: "#5c3a1a",
  },
  {
    id: "literatura",
    name: "Literatura Crioula",
    description: "Baltazar Lopes, Eugénio Tavares, Cesária Évora. Vozes que atravessam o mar.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    icon: "📖",
    color: "#2d5a1a",
  },
];

export const faces = [
  {
    id: "maria",
    name: "Maria Évora",
    island: "Santo Antão",
    role: "Produtora de grogue",
    quote:
      "Aprendi a fazer grogue com o meu pai. Hoje recebo visitantes de todo o mundo nesta destilaria.",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
  },
  {
    id: "carlos",
    name: "Carlos Tavares",
    island: "São Vicente",
    role: "Músico de morna",
    quote: "A morna não é só música. É a nossa forma de dizer ao mundo que existimos e sentimos.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
  },
  {
    id: "ana",
    name: "Ana Brito Silva",
    island: "Santiago",
    role: "Chef de cozinha crioula",
    quote: "A cachupa é como Cabo Verde: simples por fora, profunda por dentro.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
  },
  {
    id: "jose",
    name: "José Correia",
    island: "Fogo",
    role: "Viticultor do vulcão",
    quote: "O nosso vinho nasce da lava. Só em Fogo o fogo cria vida.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
  },
  {
    id: "fatima",
    name: "Fátima Monteiro",
    island: "Sal",
    role: "Guia de kitesurf",
    quote: "Ensinei centenas de pessoas a voar sobre o mar. Esta ilha é vento e liberdade.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80",
  },
  {
    id: "pedro",
    name: "Pedro Andrade",
    island: "Brava",
    role: "Contador de histórias",
    quote: "Brava é a ilha que mais viajou. A nossa diáspora carrega Cabo Verde no coração.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
  },
];

export const flavors = [
  {
    id: "cachupa",
    name: "Cachupa Rica",
    island: "Santiago",
    description: "O prato nacional. Milho, feijão, carne e legumes cozidos na perfeição.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    category: "Prato Principal",
    featured: true,
  },
  {
    id: "xerem",
    name: "Xerém",
    island: "Todas as ilhas",
    description: "Milho partido com feijão. Reconfortante e ancestral.",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    category: "Prato Principal",
  },
  {
    id: "pastel",
    name: "Pastel com Diabo Dentro",
    island: "São Vicente",
    description: "Petisco de rua inconfundível. Atum, tomate e pimenta no pastel frito.",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80",
    category: "Petisco",
  },
  {
    id: "lagosta",
    name: "Lagosta Grelhada",
    island: "Boavista / Maio",
    description: "Lagosta atlântica grelhada com manteiga e limão. Pura abundância do mar.",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
    category: "Peixe e Marisco",
  },
  {
    id: "queijo-fogo",
    name: "Queijo do Fogo",
    island: "Fogo",
    description: "Queijo de cabra com pimenta. Único no mundo, feito nos solos vulcânicos.",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80",
    category: "Produtos Locais",
  },
  {
    id: "grogue",
    name: "Grogue de Santo Antão",
    island: "Santo Antão",
    description: "Aguardente de cana-de-açúcar artesanal. A alma das montanhas em garrafa.",
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&q=80",
    category: "Bebida",
  },
  {
    id: "vinho-fogo",
    name: "Vinho do Fogo",
    island: "Fogo",
    description: "Vinho produzido na caldeira do vulcão Pico do Fogo. Mineral e único.",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80",
    category: "Bebida",
  },
];

export const playlists = [
  {
    id: "saudade",
    name: "Morna para sentir saudade",
    tracks: 14,
    duration: "58 min",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80",
    mood: "Melancólico · Atlântico",
    spotifyId: "6bHuZog5a0N2nMRC3ycMAR",
  },
  {
    id: "mindelo",
    name: "Noites de Mindelo",
    tracks: 18,
    duration: "1h 12min",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80",
    mood: "Cosmopolita · Noturno",
    spotifyId: null,
  },
  {
    id: "funana",
    name: "Funaná sem travões",
    tracks: 22,
    duration: "1h 28min",
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=400&q=80",
    mood: "Energético · Festivo",
    spotifyId: null,
  },
  {
    id: "vozes",
    name: "Vozes femininas",
    tracks: 16,
    duration: "1h 04min",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    mood: "Poderoso · Emocional",
    spotifyId: null,
  },
  {
    id: "diaspora",
    name: "Sons da diáspora",
    tracks: 20,
    duration: "1h 20min",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80",
    mood: "Mundial · Contemporâneo",
    spotifyId: null,
  },
  {
    id: "contemporaneo",
    name: "Cabo Verde contemporâneo",
    tracks: 24,
    duration: "1h 36min",
    image: "https://images.unsplash.com/photo-1526218626217-dc65a29bb444?w=400&q=80",
    mood: "Moderno · Criativo",
    spotifyId: null,
  },
];

export const events = [
  {
    id: "baia-das-gatas",
    name: "Festival Baía das Gatas",
    date: "2025-08-14",
    dateDisplay: "14–16 Ago",
    island: "São Vicente",
    location: "Baía das Gatas, Mindelo",
    category: "Música",
    description: "O maior festival de música ao ar livre de Cabo Verde. Três noites de música, mar e magia.",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    featured: true,
    free: false,
  },
  {
    id: "carnaval-mindelo",
    name: "Carnaval de Mindelo",
    date: "2025-02-25",
    dateDisplay: "25–27 Fev",
    island: "São Vicente",
    location: "Mindelo, São Vicente",
    category: "Festival",
    description: "O carnaval mais vibrante de África. Desfiles, música e cores que encantam o mundo.",
    image: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&q=80",
    featured: false,
    free: true,
  },
  {
    id: "gamboa",
    name: "Festival Gamboa",
    date: "2025-05-02",
    dateDisplay: "02–04 Mai",
    island: "Santiago",
    location: "Praia, Santiago",
    category: "Música",
    description: "Funaná, batuque e música crioula no coração da Praia.",
    image: "https://images.unsplash.com/photo-1565031491910-e57fac031c41?w=800&q=80",
    featured: false,
    free: false,
  },
  {
    id: "morna-festival",
    name: "Festival Internacional da Morna",
    date: "2025-09-27",
    dateDisplay: "27–29 Set",
    island: "São Nicolau",
    location: "Ribeira Brava, São Nicolau",
    category: "Música",
    description: "Celebração da morna, Patrimônio Cultural Imaterial da Humanidade pela UNESCO.",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    featured: false,
    free: false,
  },
  {
    id: "gastronomia-fogo",
    name: "Feira de Gastronomia do Fogo",
    date: "2025-07-12",
    dateDisplay: "12–14 Jul",
    island: "Fogo",
    location: "São Filipe, Fogo",
    category: "Gastronomia",
    description: "Vinho, queijo, grogue e a cozinha vulcânica da ilha do Fogo.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    featured: false,
    free: true,
  },
  {
    id: "arte-sal",
    name: "Expo Arte do Sal",
    date: "2025-10-18",
    dateDisplay: "18–22 Out",
    island: "Sal",
    location: "Santa Maria, Sal",
    category: "Arte",
    description: "Artistas locais e internacionais expõem junto às praias de areia branca.",
    image: "https://images.unsplash.com/photo-1555507036-ab794f575ecd?w=800&q=80",
    featured: false,
    free: true,
  },
];

export const experiences = [
  {
    id: "trekking-paul-valley",
    title: "Trekking no Vale de Paul",
    island: "Santo Antão",
    islandId: "santo-antao",
    category: "Trekking",
    duration: "6–8 horas",
    price: 45,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    description: "Percorra os trilhos míticos do Vale de Paul, entre bananeiras, canas e ribeiras de água doce. Uma das caminhadas mais belas do mundo.",
    rating: 4.9,
    difficulty: "Moderado",
    highlights: ["Guia local certificado", "Almoço incluído", "Transporte da vila", "Degustação de grogue"],
  },
  {
    id: "kitesurf-sal",
    title: "Kitesurf — Iniciação Completa",
    island: "Sal",
    islandId: "sal",
    category: "Kitesurf",
    duration: "3 dias (6h/dia)",
    price: 290,
    priceUnit: "curso completo",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80",
    description: "Aprende kitesurf com os melhores ventos do Atlântico. Sal tem condições únicas para iniciantes — vento constante e água plana.",
    rating: 4.8,
    difficulty: "Iniciante",
    highlights: ["Equipamento incluído", "Seguro de actividade", "Instructor IKO certificado", "Teoria + prática"],
  },
  {
    id: "snorkeling-santa-luzia",
    title: "Snorkeling em Santa Luzia",
    island: "São Vicente",
    islandId: "sao-vicente",
    category: "Mergulho",
    duration: "Dia inteiro",
    price: 85,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    description: "Excursão de barco à ilha desabitada de Santa Luzia. Mergulha em águas cristalinas com tartarugas, raias e polvos em ambiente virgem.",
    rating: 4.9,
    difficulty: "Fácil",
    highlights: ["Barco privado", "Equipamento de snorkeling", "Piquenique na praia", "Guia biólogo marinho"],
  },
  {
    id: "vulcao-pico-fogo",
    title: "Ascensão ao Pico do Fogo",
    island: "Fogo",
    islandId: "fogo",
    category: "Trekking",
    duration: "8–10 horas",
    price: 60,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    description: "Sobe ao cume do vulcão mais alto de Cabo Verde (2829m). Uma experiência de vida — lava negra, caldeira fumegante e vista sobre todo o arquipélago.",
    rating: 5.0,
    difficulty: "Difícil",
    highlights: ["Guia local da Chã das Caldeiras", "Equipamento de trekking", "Transporte incluído", "Certificado de ascensão"],
  },
  {
    id: "cachupa-cooking",
    title: "Aula de Cachupa com Chef Local",
    island: "Santiago",
    islandId: "santiago",
    category: "Gastronomia",
    duration: "3–4 horas",
    price: 55,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80",
    description: "Aprende a cozinhar a autêntica Cachupa Rica com uma chef de Assomada. Vai ao mercado, escolhe os ingredientes e leva a receita para casa.",
    rating: 4.7,
    difficulty: "Fácil",
    highlights: ["Visita ao mercado incluída", "Receita em papel", "Almoço da cachupa", "Vinho do Fogo de oferta"],
  },
  {
    id: "whale-watching",
    title: "Avistamento de Baleias",
    island: "São Vicente",
    islandId: "sao-vicente",
    category: "Natureza",
    duration: "4 horas",
    price: 70,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80",
    description: "Entre Janeiro e Abril, baleias-de-bossa migram pelas águas de São Vicente. Embarca num catamaran e observa estas gigantes do Atlântico.",
    rating: 4.6,
    difficulty: "Fácil",
    highlights: ["Catamaran confortável", "Hidrofone para ouvir baleias", "Guia especialista em cetáceos", "Snacks incluídos"],
  },
  {
    id: "quad-dunas-boavista",
    title: "Quad pelas Dunas da Boa Vista",
    island: "Boa Vista",
    islandId: "boa-vista",
    category: "Natureza",
    duration: "2–3 horas",
    price: 75,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "Percorre o deserto de dunas de areia dourada até ao oceano num quad 4x4. Pores do sol sobre as dunas da Boa Vista são inesquecíveis.",
    rating: 4.5,
    difficulty: "Fácil",
    highlights: ["Quad 4x4 individual", "Capacete e equipamento", "Paragem na lagoa", "Fotografia pôr do sol"],
  },
  {
    id: "noite-morna-mindelo",
    title: "Noite de Morna em Mindelo",
    island: "São Vicente",
    islandId: "sao-vicente",
    category: "Cultural",
    duration: "3–4 horas",
    price: 35,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    description: "Vive a morna ao vivo num espaço histórico de Mindelo. Músicos de viola d'arco, cantiga e gaita — Património UNESCO em ambiente íntimo.",
    rating: 4.9,
    difficulty: "Fácil",
    highlights: ["Concerto ao vivo de 2h", "Introdução à morna", "Jantar crioulo opcional", "Conversa com músicos"],
  },
  {
    id: "tartarugas-boavista",
    title: "Vigília das Tartarugas",
    island: "Boa Vista",
    islandId: "boa-vista",
    category: "Natureza",
    duration: "4–6 horas (nocturno)",
    price: 50,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&q=80",
    description: "Entre Junho e Outubro, tartarugas-marinhas desovam nas praias da Boa Vista. Acompanha biólogos marinhos numa vigília nocturna emocionante.",
    rating: 4.8,
    difficulty: "Fácil",
    highlights: ["Guia biólogo marinho", "Lanterna especial de baixa intensidade", "Certificado de conservação", "Transporte incluído"],
  },
  {
    id: "pesca-alto-mar",
    title: "Pesca de Alto Mar",
    island: "Sal",
    islandId: "sal",
    category: "Natureza",
    duration: "6–8 horas",
    price: 120,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800&q=80",
    description: "Pesca desportiva de marlim, atum e wahoo nas ricas águas atlânticas de Cabo Verde. Barco equipado com tudo o que precisas.",
    rating: 4.6,
    difficulty: "Moderado",
    highlights: ["Barco equipado de 9m", "Equipamento de pesca", "Almoço a bordo", "Peixe grelhado no regresso"],
  },
  {
    id: "cidade-velha-tour",
    title: "Tour Histórico da Cidade Velha",
    island: "Santiago",
    islandId: "santiago",
    category: "Cultural",
    duration: "3 horas",
    price: 30,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "Visita guiada à primeira cidade colonial europeia nos trópicos, Patrimônio Mundial da UNESCO. Pelourinho, Sé Catedral e o Forte Real de São Filipe.",
    rating: 4.7,
    difficulty: "Fácil",
    highlights: ["Guia historiador", "Entrada no Forte incluída", "Documentário histórico", "Livro de história de oferta"],
  },
  {
    id: "mergulho-boa-vista",
    title: "Mergulho — Baptismo Submarino",
    island: "Boa Vista",
    islandId: "boa-vista",
    category: "Mergulho",
    duration: "3–4 horas",
    price: 95,
    priceUnit: "por pessoa",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    description: "O teu primeiro mergulho em águas do Atlântico. Instrutores PADI levam-te a descobrir recifes, mantas e o silêncio mágico do fundo do mar.",
    rating: 4.8,
    difficulty: "Iniciante",
    highlights: ["Instrutor PADI certificado", "Equipamento completo incluído", "Sessão teórica de 1h", "Fotografia subaquática"],
  },
];

export const partners = [
  {
    id: "hotel-morabeza",
    name: "Hotel Morabeza",
    type: "Hotel",
    island: "Sal",
    islandId: "sal",
    description: "Boutique hotel junto à Praia de Santa Maria. Arquitectura local, piscina infinita e o melhor pôr do sol do Atlântico.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    verified: true,
    badge: "Parceiro Oficial",
    website: "https://hotelmorabeza.cv",
  },
  {
    id: "mindelo-resto-art",
    name: "Mindelo Resto Art",
    type: "Restaurante",
    island: "São Vicente",
    islandId: "sao-vicente",
    description: "Restaurante no coração de Mindelo com cozinha crioula de autor. Pastel com diabo dentro, morna ao vivo às sextas.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    verified: true,
    badge: "Recomendado",
    website: "https://mindelorestoa.rt",
  },
  {
    id: "cabo-verde-trek",
    name: "Cabo Verde Trek",
    type: "Operador Turístico",
    island: "Santo Antão",
    islandId: "santo-antao",
    description: "Especialistas em trekking de montanha em Santo Antão. Guias locais com mais de 15 anos de experiência nos trilhos de Paul e Ribeira Grande.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    verified: true,
    badge: "Parceiro Oficial",
    website: "https://caboverdetrek.cv",
  },
  {
    id: "surf-zone-sal",
    name: "Surf Zone Sal",
    type: "Escola de Desporto",
    island: "Sal",
    islandId: "sal",
    description: "Escola de kitesurf, windsurf e surf. Instrutores certificados IKO e VDWS. O melhor lugar para aprender com ventos aliseus constantes.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    verified: true,
    badge: "Certificado IKO",
    website: "https://surfzonessal.cv",
  },
  {
    id: "casa-velha-boutique",
    name: "Casa Velha Boutique",
    type: "Hotel",
    island: "Santiago",
    islandId: "santiago",
    description: "Hotel boutique no centro histórico da Praia. Casa colonial restaurada com vista para o Platô. Café da manhã com produção local.",
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80",
    verified: true,
    badge: "Recomendado",
    website: "https://casavelhacv.com",
  },
  {
    id: "a-terra-fogo",
    name: "A Terra — Enoturismo",
    type: "Restaurante",
    island: "Fogo",
    islandId: "fogo",
    description: "Restaurante da cooperativa vinícola da Chã das Caldeiras. Vinho do Fogo, queijo local e pratos feitos com legumes cultivados em solo vulcânico.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    verified: true,
    badge: "Experiência Única",
    website: "https://aterrafogo.cv",
  },
  {
    id: "atlantis-dive",
    name: "Atlantis Dive Center",
    type: "Operador Turístico",
    island: "Boa Vista",
    islandId: "boa-vista",
    description: "Centro de mergulho PADI referência em Cabo Verde. Baptismos, cursos Open Water, mergulho nocturno e avistamento de mantas-raias.",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    verified: true,
    badge: "PADI 5 Stars",
    website: "https://atlantisdiiecv.com",
  },
  {
    id: "windclub-boavista",
    name: "Windclub Boa Vista",
    type: "Escola de Desporto",
    island: "Boa Vista",
    islandId: "boa-vista",
    description: "Kitesurf, windsurf e stand-up paddle nas dunas da Boa Vista. Aluguer de equipamento e aulas para todos os níveis.",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80",
    verified: false,
    badge: "Parceiro",
    website: "https://windclubboavista.cv",
  },
  {
    id: "enoturismo-fogo",
    name: "Caves du Fogo",
    type: "Operador Turístico",
    island: "Fogo",
    islandId: "fogo",
    description: "Tours de enoturismo na caldeira do vulcão. Visita às vinhas, adega, degustação guiada e piquenique entre lavas.",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80",
    verified: true,
    badge: "Experiência Única",
    website: "https://cavesdufogo.cv",
  },
  {
    id: "pensao-brava",
    name: "Pensão das Flores",
    type: "Hotel",
    island: "Brava",
    islandId: "brava",
    description: "Pensão familiar em Nova Sintra, a capital das flores. Vista para o vale, jardins de hortênsias e a hospitalidade autêntica da ilha mais pequena.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    verified: false,
    badge: "Parceiro",
    website: "https://pensaodasflores.cv",
  },
];

export const diasporaCommunities = [
  {
    id: "portugal",
    country: "Portugal",
    flag: "🇵🇹",
    city: "Lisboa · Porto · Amadora",
    population: "150 000+",
    populationNumber: 150000,
    description: "A maior comunidade fora das ilhas. Lisboa tem bairros inteiros marcados pela cultura cabo-verdiana — Cova da Moura, Bairro da Jamaica, Damaia.",
    highlight: "A morna toca nas tascas de Alfama como se fosse sempre Mindelo",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
    islandRoots: ["Santiago", "São Vicente", "Santo Antão", "Fogo"],
  },
  {
    id: "eua",
    country: "Estados Unidos",
    flag: "🇺🇸",
    city: "New Bedford · Boston · Providence",
    population: "500 000+",
    populationNumber: 500000,
    description: "New Bedford, Massachusetts, é considerada a capital da diáspora americana. Os antepassados chegaram nos navios baleeiros do século XIX.",
    highlight: "Os primeiros cabo-verdianos chegaram como baleeiros em 1800",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&q=80",
    islandRoots: ["Brava", "Fogo", "São Nicolau"],
  },
  {
    id: "franca",
    country: "França",
    flag: "🇫🇷",
    city: "Paris · Marselha · Lyon",
    population: "90 000+",
    populationNumber: 90000,
    description: "Paris acolhe uma comunidade vibrante concentrada em Seine-Saint-Denis. Associações culturais mantêm viva a língua crioula e as tradições.",
    highlight: "Cesária Évora gravou os seus álbuns em Paris, na rue Championnet",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    islandRoots: ["Santiago", "São Vicente", "Fogo"],
  },
  {
    id: "paises-baixos",
    country: "Países Baixos",
    flag: "🇳🇱",
    city: "Roterdão · Haia · Amesterdão",
    population: "40 000+",
    populationNumber: 40000,
    description: "Roterdão tem a maior comunidade cabo-verdiana nos Países Baixos. O Carnaval de Roterdão tem cada vez mais influência cabo-verdiana.",
    highlight: "Uma em cada dez famílias de Roterdão tem raízes em Cabo Verde",
    image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&q=80",
    islandRoots: ["Santiago", "São Vicente"],
  },
  {
    id: "italia",
    country: "Itália",
    flag: "🇮🇹",
    city: "Milão · Turim · Roma",
    population: "80 000+",
    populationNumber: 80000,
    description: "A Itália acolheu uma das diásporas mais recentes, sobretudo após os anos 90. Comunidades bem organizadas com associações culturais activas.",
    highlight: "O funaná toca em festas italo-cabo-verdianas por todo o norte de Itália",
    image: "https://images.unsplash.com/photo-1525874684015-58379d421a52?w=800&q=80",
    islandRoots: ["Santiago", "Santo Antão", "São Nicolau"],
  },
  {
    id: "luxemburgo",
    country: "Luxemburgo",
    flag: "🇱🇺",
    city: "Cidade do Luxemburgo · Esch-sur-Alzette",
    population: "12 000+",
    populationNumber: 12000,
    description: "Uma das comunidades mais pequenas mas mais coesas. Luxemburgo tem uma das mais altas proporções de cabo-verdianos por habitante na Europa.",
    highlight: "Cada família tem uma história de mobilidade e de raízes profundas",
    image: "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=800&q=80",
    islandRoots: ["Santo Antão", "São Vicente", "Santiago"],
  },
  {
    id: "angola",
    country: "Angola",
    flag: "🇦🇴",
    city: "Luanda · Lobito · Benguela",
    population: "30 000+",
    populationNumber: 30000,
    description: "Uma comunidade com raízes profundas no período colonial. Cabo-verdianos chegaram como professores, administradores e técnicos — e ficaram. Hoje integram-se na sociedade angolana sem perderem a identidade das ilhas.",
    highlight: "Em Luanda, o crioulo mistura-se com o quimbundo nas noites da Ilha — Cabo Verde está sempre presente",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    islandRoots: ["Santiago", "São Vicente", "Fogo", "Santo Antão"],
  },
  {
    id: "senegal",
    country: "Senegal",
    flag: "🇸🇳",
    city: "Dakar · Ziguinchor",
    population: "25 000+",
    populationNumber: 25000,
    description: "A comunidade africana mais próxima das ilhas. Cabo-verdianos e senegaleses partilham séculos de história comercial e cultural.",
    highlight: "Dakar foi durante séculos o porto de passagem entre as ilhas e o mundo",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
    islandRoots: ["Santiago", "São Vicente"],
  },
  {
    id: "brasil",
    country: "Brasil",
    flag: "🇧🇷",
    city: "São Paulo · Rio de Janeiro",
    population: "15 000+",
    populationNumber: 15000,
    description: "Ligações históricas através do Atlântico Sul. A música cabo-verdiana e a brasileira partilham raízes africanas comuns que se reconhecem imediatamente.",
    highlight: "O crioulo e o português brasileiro entendem-se como primos que se reencontram",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
    islandRoots: ["Fogo", "Brava", "São Nicolau"],
  },
];

export const diasporaStories = [
  {
    id: "amelia-newbedford",
    name: "Amélia Tavares",
    age: 62,
    country: "Estados Unidos",
    flag: "🇺🇸",
    city: "New Bedford, Massachusetts",
    islandOrigin: "Brava",
    quote: "O meu avô partiu de Brava em 1923 num barco baleeiro. Nunca voltou a ver a ilha. Mas eu voltei por ele. Chorei o tempo todo.",
    detail: "Amélia é professora de português e dirige o Museu Luso-Americano de New Bedford. Os seus pais emigraram nos anos 60.",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
    yearsAway: 40,
  },
  {
    id: "nuno-rotterdam",
    name: "Nuno Évora",
    age: 34,
    country: "Países Baixos",
    flag: "🇳🇱",
    city: "Roterdão",
    islandOrigin: "Santiago",
    quote: "Cresci em Roterdão mas o meu coração é crioulo. Quando ouço batuque, qualquer coisa dentro de mim acorda.",
    detail: "Nuno é DJ e produtor musical. Mistura funaná com electrónica europeia e toca em festivais por toda a Europa.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    yearsAway: 0,
  },
  {
    id: "fatou-paris",
    name: "Fátou Semedo",
    age: 29,
    country: "França",
    flag: "🇫🇷",
    city: "Paris",
    islandOrigin: "São Vicente",
    quote: "Eles dizem-me que sou francesa. Mas quando regresso a Mindelo, percebo que sou cabo-verdiana que vive em França.",
    detail: "Fátou é arquitecta e fundou uma plataforma de design que celebra a estética crioula contemporânea.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
    yearsAway: 8,
  },
  {
    id: "jorge-luxemburgo",
    name: "Jorge Monteiro",
    age: 55,
    country: "Luxemburgo",
    flag: "🇱🇺",
    city: "Esch-sur-Alzette",
    islandOrigin: "Santo Antão",
    quote: "Cheguei com 17 anos sem falar uma palavra de francês. Hoje sou presidente da associação cabo-verdiana do Luxemburgo.",
    detail: "Jorge lidera a maior associação cultural cabo-verdiana no Luxemburgo, com mais de 800 membros.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
    yearsAway: 38,
  },
  {
    id: "ines-lisboa",
    name: "Inês Borges",
    age: 24,
    country: "Portugal",
    flag: "🇵🇹",
    city: "Lisboa",
    islandOrigin: "Fogo",
    quote: "Os meus pais vieram do Fogo. Eu nasci em Lisboa mas o vulcão é a minha origem. É de onde venho quando me perguntam quem sou.",
    detail: "Inês estuda antropologia e investiga a identidade da geração de cabo-verdianos nascidos na diáspora.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80",
    yearsAway: 0,
  },
];

export const diasporaEvents = [
  {
    id: "kriolu-world-lisboa",
    name: "Kriolu World Lisboa",
    date: "2025-06-14",
    dateDisplay: "14–16 Jun",
    country: "Portugal",
    flag: "🇵🇹",
    city: "Lisboa, Parque das Nações",
    description: "O maior festival da diáspora cabo-verdiana na Europa. Música, gastronomia, artesanato e debates sobre a identidade crioula contemporânea.",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    category: "Festival",
    free: false,
  },
  {
    id: "cape-verdean-day-boston",
    name: "Cape Verdean Day",
    date: "2025-07-04",
    dateDisplay: "04 Jul",
    country: "Estados Unidos",
    flag: "🇺🇸",
    city: "New Bedford, Massachusetts",
    description: "Celebração anual da herança cabo-verdiana em New Bedford. Desfiles, comida crioula, música e storytelling da comunidade.",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&q=80",
    category: "Cultural",
    free: true,
  },
  {
    id: "noite-crioula-paris",
    name: "Noite Crioula de Paris",
    date: "2025-09-20",
    dateDisplay: "20 Set",
    country: "França",
    flag: "🇫🇷",
    city: "Paris, Théâtre de la Ville",
    description: "Concerto anual que celebra a música cabo-verdiana em Paris. Artistas das ilhas e da diáspora num programa que vai da morna ao funaná.",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    category: "Música",
    free: false,
  },
  {
    id: "carnaval-rotterdam",
    name: "Carnaval de Roterdão — Bloco Crioulo",
    date: "2025-08-02",
    dateDisplay: "02 Ago",
    country: "Países Baixos",
    flag: "🇳🇱",
    city: "Roterdão",
    description: "O Bloco Crioulo é o grupo cabo-verdiano do Carnaval de Roterdão. Fantasias, batuque e a energia do Carnaval de Mindelo transportada para a Holanda.",
    image: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&q=80",
    category: "Carnaval",
    free: true,
  },
];

export const editorialFeatures = [
  {
    id: "featured-story",
    type: "história",
    title: "A voz que atravessou o Atlântico: o legado de Cesária Évora",
    subtitle: "Como uma mulher de São Vicente se tornou o rosto do mundo.",
    island: "São Vicente",
    image: "/images/cesaria-evora.png",
    readTime: "8 min",
    featured: true,
    body: [
      {
        paragraphs: [
          `Dizer que Cesária Évora levou Cabo Verde ao mundo é reduzir a imensidão do seu impacto. Ela não apenas apresentou as ilhas ao mapa internacional; ela fez o mundo inteiro sentir a melancolia, a dignidade e a doçura da alma cabo-verdiana através da sua voz única. Mais de uma década depois da sua partida, essa voz continua a atravessar oceanos, gerações e línguas, provando que existe uma forma de arte que não precisa de tradução para tocar o coração.`,
        ],
      },
      {
        heading: "Das ruas de Mindelo ao silêncio dos bares",
        paragraphs: [
          `Cesária Évora nasceu a 27 de agosto de 1941, em Mindelo, na ilha de São Vicente — a mesma cidade que, décadas depois, se tornaria sinónimo do seu nome. Cresceu numa família humilde e musical: o pai, Justino da Cruz, tocava cavaquinho, violão e violino, e entre as suas amizades de infância contava-se nada menos que B. Leza, o compositor mais reverenciado da morna cabo-verdiana, que viria a falecer quando Cesária tinha apenas sete anos.`,
          `Ainda adolescente, começou a cantar aos domingos na praça principal de Mindelo, acompanhada pelo irmão Lela ao saxofone. Foi um marinheiro chamado Eduardo quem, quando ela tinha dezasseis anos, lhe ensinou os estilos tradicionais que marcariam toda a sua carreira: a morna e a coladera. Dali em diante, os bares e hotéis do bairro do Lombo — junto aos aquartelamentos do exército português — tornaram-se o seu verdadeiro conservatório. Cantava por necessidade e por vocação, ganhando aos poucos a reputação de "Rainha da Morna" entre os que a ouviam, mesmo sem qualquer projeção fora do arquipélago.`,
          `Durante quase duas décadas, essa foi a sua realidade: uma voz extraordinária confinada à escala local, cantando as dores e as esperanças do seu povo sem que o resto do mundo soubesse da sua existência.`,
        ],
      },
      {
        heading: "O reconhecimento tardio que não mudou nada",
        paragraphs: [
          `A viragem só chegaria nos anos 1980, quando o produtor José da Silva a descobriu e a levou para Paris. Em 1988, já com 47 anos, gravou o seu primeiro álbum internacional, La Diva Aux Pieds Nus — "A Diva dos Pés Descalços". O título não era um simples adorno artístico: descrevia literalmente o que Cesária fazia em palco. Recusava-se a calçar sapatos nos concertos, mesmo nos palcos mais prestigiados do mundo, como o Olympia de Paris ou o Carnegie Hall em Nova Iorque, em solidariedade com os sem-teto e os mais desfavorecidos da sua terra natal.`,
          `É notável que o reconhecimento internacional tenha chegado tão tarde — depois de mais de cinquenta anos de vida — e ainda mais notável é o facto de esse sucesso repentino não lhe ter alterado a essência. Cesária continuava a ser, em palco e fora dele, a mesma mulher simples de Mindelo. Álbuns como Miss Perfumado (1992) e Cesária (1995) consolidaram-na como fenómeno global, e a sua voz rouca e contralto tornou-se inconfundível em qualquer parte do mundo.`,
        ],
      },
      {
        heading: "A Morna como património universal",
        paragraphs: [
          `A Morna é, antes de mais, uma forma de lamento — o próprio nome deriva possivelmente do inglês mourn. É a expressão máxima da saudade crioula: um género que fala de partida, de distância, de amores impossíveis e do eterno desejo de regressar a casa. Antes de Cesária, a morna era um tesouro local, conhecido essencialmente dentro do arquipélago e da diáspora cabo-verdiana. Depois de Cesária, tornou-se património universal.`,
          `A sua interpretação de "Sodade" — talvez a canção mais emblemática de toda a música cabo-verdiana — transformou-se num hino global da diáspora. Não é preciso compreender crioulo para sentir o peso daquela palavra intraduzível: sodade é mais do que saudade, é uma ausência que dói no corpo. Outras canções, como "Petit Pays" e a sua versão pessoal de "Bésame Mucho", ampliaram ainda mais o alcance do seu repertório, misturando influências africanas, portuguesas e latino-americanas numa síntese que só ela sabia fazer soar natural.`,
          `O reconhecimento da crítica internacional acompanhou este percurso: um Grammy de Melhor Álbum de World Music Contemporânea em 2004, pelo álbum Voz d'Amor; duas vitórias no prémio francês Victoires de la Musique; a Medalha da Legião de Honra de França; a Grã-Cruz da Ordem do Infante D. Henrique, atribuída por Portugal; e a Ordem de Mérito Cultural do Brasil, entre muitas outras distinções. Vendeu mais de oito milhões de discos em todo o mundo — números impensáveis para uma artista que, até aos quarenta anos, cantava apenas para o público dos bares de Mindelo.`,
        ],
      },
      {
        heading: "Um símbolo que ultrapassa a música",
        paragraphs: [
          `Cesária Évora faleceu a 17 de dezembro de 2011, aos 70 anos, em Mindelo — fechando o círculo entre o ponto de partida e o ponto de chegada da sua vida. Como forma de homenagem póstuma, o aeroporto internacional de São Vicente passou a ostentar o seu nome a partir de 2012, e uma estátua sua recebe hoje quem chega às ilhas pelo ar, como se ela continuasse a dar as boas-vindas a cada visitante.`,
          `Mas o legado de Cesária vai muito além dos prémios e das honrarias oficiais. Ela é a prova viva de que a arte mais genuína nasce da verdade e da ligação profunda às próprias raízes — não da tentativa de agradar a um mercado internacional. Cantou sempre em crioulo, nunca abdicou dos seus pés descalços, e nunca deixou de ser, essencialmente, uma mulher de Mindelo que encontrou o mundo tarde, mas encontrou-o nos seus próprios termos.`,
          `A sua voz permanece viva — gravada no vento que sopra pelo arquipélago, nas rádios da diáspora espalhada pelo mundo, e na identidade de um povo que continua a cantar para não chorar. Cesária Évora foi, e continuará a ser, a voz que aproximou as duas margens do Atlântico.`,
        ],
      },
    ],
  },
  {
    id: "ilha-semana",
    type: "ilha da semana",
    title: "Fogo: A beleza que nasce da destruição",
    subtitle: "Onde o vulcão e a vida coexistem em harmonia perfeita.",
    island: "Fogo",
    image: "/images/fogo.png",
    readTime: "5 min",
    featured: false,
    body: [
      {
        paragraphs: [
          `A ilha do Fogo é uma das maravilhas naturais mais extraordinárias do Atlântico. O Pico do Fogo, com os seus 2.829 metros, domina a paisagem de forma majestosa e ameaçadora ao mesmo tempo — a última grande erupção vulcânica deu-se em 2014 e durou meses, obrigando a evacuação de milhares de pessoas. E, no entanto, eles voltaram. Sempre voltam.`,
        ],
      },
      {
        heading: "O vinho que nasce da lava",
        paragraphs: [
          `O vinho de Fogo, produzido nas encostas da Chã das Caldeiras pelos habitantes que vivem literalmente dentro da caldeira do vulcão, é hoje reconhecido internacionalmente como um dos vinhos mais incomuns do mundo. A terra negra vulcânica, rica em minerais, confere-lhe um carácter único e inimitável.`,
          `Visitar Fogo é perceber que os cabo-verdianos aprenderam a viver com a incerteza como quem aprende a dançar na chuva. A beleza que nasce da destruição não é uma metáfora — é a realidade diária desta ilha que se reinventa depois de cada catástrofe.`,
        ],
      },
    ],
  },
  {
    id: "artista-mes",
    type: "artista do mês",
    title: "Mayra Andrade: A nova voz do Atlântico",
    subtitle: "De Santiago para o mundo com a morna no coração.",
    island: "Santiago",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80",
    readTime: "4 min",
    featured: false,
    body: [
      {
        paragraphs: [
          `Nascida em Havana mas criada em Santiago de Cabo Verde, Mayra Andrade é a prova de que a música cabo-verdiana tem futuro tão rico quanto o seu passado. Com uma voz que mistura a herança da morna com influências de jazz, soul e músicas do mundo, tornou-se num dos maiores nomes da música lusófona contemporânea.`,
        ],
      },
      {
        heading: "Uma voz para o futuro",
        paragraphs: [
          `Desde o seu álbum de estreia, Navega (2006), Mayra revelou uma capacidade rara de reinterpretar o cânone tradicional sem o trair. As suas actuações ao vivo — desde o festival de Montreux ao Barbican em Londres — confirmam uma presença em palco que vai muito além da voz.`,
          `Com Mayra Andrade, Cabo Verde não perdeu Cesária Évora. Ganhou a sua herdeira espiritual — diferente nos sons, igual na capacidade de fazer o mundo parar para ouvir.`,
        ],
      },
    ],
  },
  {
    id: "receita",
    type: "receita da semana",
    title: "Cachupa Rica: a receita da avó de Assomada",
    subtitle: "Passo a passo do prato mais amado de Cabo Verde.",
    island: "Santiago",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    readTime: "6 min",
    featured: false,
    body: [
      {
        paragraphs: [
          `A cachupa rica é o coração da cozinha cabo-verdiana. Mais do que um prato, é um ritual — uma reunião à volta de um tacho que ferve lentamente durante horas, enchendo a casa de aromas que fazem chamar as saudades. É comida que pede tempo e exige atenção, como todas as coisas que valem a pena.`,
        ],
      },
      {
        heading: "A receita que não tem medida certa",
        paragraphs: [
          `Ao contrário da cachupa pobre, que se faz com milho, feijões e poucos mais ingredientes, a cachupa rica celebra a abundância: leva chouriço, linguiça, entrecosto, bacon, bucho, e tudo o que a despensa puder oferecer. A versão da avó de Assomada, na ilha de Santiago, é passada de geração em geração com a naturalidade de quem ensina uma língua materna.`,
          `Conta-se que a cachupa fica sempre melhor no dia seguinte — aquecida na frigideira, com um ovo frito por cima. E que cada família tem a sua versão, a única versão verdadeira, naturalmente.`,
        ],
      },
    ],
  },
];
